"""create_trainee_tables

Revision ID: 361040002dd6
Revises: 42c6c4df26af
Create Date: 2026-05-19 13:59:53.920477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '361040002dd6'
down_revision: Union[str, Sequence[str], None] = '42c6c4df26af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop legacy tables first to free up the custom enum types
    op.drop_table('student_tasks')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_table('students')
    
    # Drop old type enums to prevent duplicate object errors
    op.execute("DROP TYPE IF EXISTS userrole CASCADE")
    op.execute("DROP TYPE IF EXISTS taskstatus CASCADE")

    op.create_table('trainees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trainee_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TRAINEE', name='userrole'), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('technologies', sa.JSON(), nullable=False),
    sa.Column('hackerrank_username', sa.String(length=100), nullable=True),
    sa.Column('hackerrank_score', sa.Integer(), nullable=False),
    sa.Column('hackerrank_solved', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainees_email'), 'trainees', ['email'], unique=True)
    op.create_table('trainee_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trainee_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('COMPLETED', 'IN_PROGRESS', 'NOT_STARTED', 'DOES_NOT_APPLY', name='taskstatus'), nullable=False),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainee_id'], ['trainees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainee_id', 'task_id', name='uq_trainee_task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'STUDENT', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('joining_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('students_pkey'))
    )
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_table('student_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('COMPLETED', 'IN_PROGRESS', 'NOT_STARTED', 'DOES_NOT_APPLY', name='taskstatus'), autoincrement=False, nullable=False),
    sa.Column('assigned_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('completion_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('student_tasks_student_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('student_tasks_task_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_tasks_pkey')),
    sa.UniqueConstraint('student_id', 'task_id', name=op.f('uq_student_task'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('trainee_tasks')
    op.drop_index(op.f('ix_trainees_email'), table_name='trainees')
    op.drop_table('trainees')
    # ### end Alembic commands ###
